package com.micdm.transportlive.events;

public enum EventType {
    REQUEST_RECONNECT,
    REQUEST_LOAD_SERVICE,
    LOAD_SERVICE,
    REQUEST_LOAD_ROUTES,
    LOAD_ROUTES,
    REQUEST_SELECT_ROUTE,
    REQUEST_UNSELECT_ROUTE,
    REQUEST_LOAD_VEHICLES,
    LOAD_VEHICLES,
    REQUEST_LOAD_STATIONS,
    LOAD_STATIONS,
    REQUEST_SELECT_STATION,
    REQUEST_UNSELECT_STATION,
    REQUEST_LOAD_FORECASTS,
    LOAD_FORECASTS,
    REQUEST_LOAD_DONATE_PRODUCTS,
    LOAD_DONATE_PRODUCTS,
    REQUEST_DONATE,
    DONATE,
}
