package com.micdm.transportlive.events;

public enum EventType {
    REQUEST_LOAD_SERVICE,
    LOAD_SERVICE,
    REQUEST_LOAD_ROUTES,
    LOAD_ROUTES,
    REQUEST_SELECT_ROUTE,
    REQUEST_UNSELECT_ROUTE,
    UNSELECT_ROUTE,
    UPDATE_VEHICLE,
    REMOVE_VEHICLE,
    REQUEST_LOAD_STATIONS,
    LOAD_STATIONS,
    REQUEST_SELECT_STATION,
    REQUEST_UNSELECT_STATION,
    UPDATE_FORECAST,
    REQUEST_FOCUS_VEHICLE,
    REMOVE_ALL_DATA,
    REQUEST_LOAD_DONATE_PRODUCTS,
    LOAD_DONATE_PRODUCTS,
    REQUEST_DONATE,
    DONATE,
}
